swagger: '2.0'
info:
  title: Argent Bank API
  description: Main endpoints for authentication, profile and transactions
  version: '1.0.0'
host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:
  /user/login:
    post:
      summary: Login
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Login'
      responses:
        '200':
          description: Login success
          schema:
            $ref: '#/definitions/LoginResponse'
        '400': { description: Invalid fields }

  /user/signup:
    post:
      summary: Signup
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/User'
      responses:
        '200': { description: Signup success }

  /user/profile:
    post:
      summary: Get profile
      security: [ { Bearer: [] } ]
      responses:
        '200': { description: Profile retrieved }
    put:
      summary: Update profile
      security: [ { Bearer: [] } ]
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/UserProfile'
      responses:
        '200': { description: Profile updated }

  /transactions:
    get:
      summary: Get all transactions
      security: [ { Bearer: [] } ]
      responses:
        '200':
          description: List of transactions
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'

  /transactions/{transactionId}:
    get:
      summary: Get transaction by ID
      security: [ { Bearer: [] } ]
      parameters:
        - in: path
          name: transactionId
          type: string
      responses:
        '200': { description: Transaction details }
    patch:
      summary: Update transaction
      security: [ { Bearer: [] } ]
      parameters:
        - in: path
          name: transactionId
          type: string
        - in: body
          name: body
          schema:
            $ref: '#/definitions/TransactionUpdate'
      responses:
        '200': { description: Transaction updated }

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    properties:
      email: { type: string }
      password: { type: string }
      firstName: { type: string }
      lastName: { type: string }
      userName: { type: string }

  Login:
    properties:
      email: { type: string }
      password: { type: string }

  LoginResponse:
    properties:
      token: { type: string }

  UserProfile:
    properties:
      userName: { type: string }

  Transaction:
    properties:
      id: { type: string }
      date: { type: string, format: date-time }
      description: { type: string }
      amount: { type: number }
      type: { type: string }
      category: { type: string }
      notes: { type: string }

  TransactionUpdate:
    properties:
      category: { type: string }
      notes: { type: string }
